# CodeRabbit Configuration
version: "0.1"

reviews:
# Enable high-level summary
high_level_summary: true

# Review the changes in the context of the entire file
verification_status: true

# Auto-review behavior
auto_review:
enabled: true
drafts: false

chat:
auto_reply: true

# Knowledge base for context (optional)
# knowledge_base:
# - name: "ProjectContext"
# file: "README.md"