reviews:
-# Enable high-level summary
-high_level_summary: true
-
-# Review the changes in the context of the entire file
-auto_review:
    enabled: true
    drafts: false
+  high_level_summary: true
+
+ chat:
+   auto_reply: true